//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica5_prog3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia
    {
        public int codigo { get; set; }
        public string materia1 { get; set; }
        public Nullable<int> id_estudiante { get; set; }
    
        public virtual estudiante estudiante { get; set; }
    }


}
